package com.htsc.hub.db.model;

public class StockShareholding {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_shareholding.Id
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_shareholding.date
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	private String date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_shareholding.code
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_shareholding.amount
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_shareholding.price
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_shareholding.type
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_shareholding.Id
	 * @return  the value of stock_shareholding.Id
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_shareholding.Id
	 * @param id  the value for stock_shareholding.Id
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_shareholding.date
	 * @return  the value of stock_shareholding.date
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_shareholding.date
	 * @param date  the value for stock_shareholding.date
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_shareholding.code
	 * @return  the value of stock_shareholding.code
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_shareholding.code
	 * @param code  the value for stock_shareholding.code
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_shareholding.amount
	 * @return  the value of stock_shareholding.amount
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_shareholding.amount
	 * @param amount  the value for stock_shareholding.amount
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_shareholding.price
	 * @return  the value of stock_shareholding.price
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_shareholding.price
	 * @param price  the value for stock_shareholding.price
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_shareholding.type
	 * @return  the value of stock_shareholding.type
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_shareholding.type
	 * @param type  the value for stock_shareholding.type
	 * @mbggenerated  Wed Feb 10 11:01:21 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}
}