package com.htsc.hub.db.model;

public class StockChoose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_choose.Id
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_choose.code
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_choose.date
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_choose.Id
     *
     * @return the value of stock_choose.Id
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_choose.Id
     *
     * @param id the value for stock_choose.Id
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_choose.code
     *
     * @return the value of stock_choose.code
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_choose.code
     *
     * @param code the value for stock_choose.code
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_choose.date
     *
     * @return the value of stock_choose.date
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_choose.date
     *
     * @param date the value for stock_choose.date
     *
     * @mbggenerated Wed Feb 10 08:38:17 CST 2016
     */
    public void setDate(String date) {
        this.date = date;
    }
}