package com.htsc.hub.db.model;

public class StockWeekQuotation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_week_quotation.code
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_week_quotation.name
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_week_quotation.date
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	private String date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_week_quotation.open
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	private Float open;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_week_quotation.high
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	private Float high;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_week_quotation.close
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	private Float close;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_week_quotation.low
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	private Float low;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_week_quotation.code
	 * @return  the value of stock_week_quotation.code
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_week_quotation.code
	 * @param code  the value for stock_week_quotation.code
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_week_quotation.name
	 * @return  the value of stock_week_quotation.name
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_week_quotation.name
	 * @param name  the value for stock_week_quotation.name
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_week_quotation.date
	 * @return  the value of stock_week_quotation.date
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_week_quotation.date
	 * @param date  the value for stock_week_quotation.date
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_week_quotation.open
	 * @return  the value of stock_week_quotation.open
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public Float getOpen() {
		return open;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_week_quotation.open
	 * @param open  the value for stock_week_quotation.open
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public void setOpen(Float open) {
		this.open = open;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_week_quotation.high
	 * @return  the value of stock_week_quotation.high
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public Float getHigh() {
		return high;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_week_quotation.high
	 * @param high  the value for stock_week_quotation.high
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public void setHigh(Float high) {
		this.high = high;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_week_quotation.close
	 * @return  the value of stock_week_quotation.close
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public Float getClose() {
		return close;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_week_quotation.close
	 * @param close  the value for stock_week_quotation.close
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public void setClose(Float close) {
		this.close = close;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_week_quotation.low
	 * @return  the value of stock_week_quotation.low
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public Float getLow() {
		return low;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_week_quotation.low
	 * @param low  the value for stock_week_quotation.low
	 * @mbggenerated  Wed Feb 17 14:33:08 CST 2016
	 */
	public void setLow(Float low) {
		this.low = low;
	}
}