package com.htsc.hub.db.model;

import java.util.ArrayList;
import java.util.List;

public class StockQuotationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public StockQuotationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(String value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(String value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(String value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(String value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(String value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(String value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLike(String value) {
            addCriterion("date like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotLike(String value) {
            addCriterion("date not like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<String> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<String> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(String value1, String value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(String value1, String value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andOpenIsNull() {
            addCriterion("open is null");
            return (Criteria) this;
        }

        public Criteria andOpenIsNotNull() {
            addCriterion("open is not null");
            return (Criteria) this;
        }

        public Criteria andOpenEqualTo(Double value) {
            addCriterion("open =", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotEqualTo(Double value) {
            addCriterion("open <>", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenGreaterThan(Double value) {
            addCriterion("open >", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenGreaterThanOrEqualTo(Double value) {
            addCriterion("open >=", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenLessThan(Double value) {
            addCriterion("open <", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenLessThanOrEqualTo(Double value) {
            addCriterion("open <=", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenIn(List<Double> values) {
            addCriterion("open in", values, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotIn(List<Double> values) {
            addCriterion("open not in", values, "open");
            return (Criteria) this;
        }

        public Criteria andOpenBetween(Double value1, Double value2) {
            addCriterion("open between", value1, value2, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotBetween(Double value1, Double value2) {
            addCriterion("open not between", value1, value2, "open");
            return (Criteria) this;
        }

        public Criteria andHighIsNull() {
            addCriterion("high is null");
            return (Criteria) this;
        }

        public Criteria andHighIsNotNull() {
            addCriterion("high is not null");
            return (Criteria) this;
        }

        public Criteria andHighEqualTo(Double value) {
            addCriterion("high =", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotEqualTo(Double value) {
            addCriterion("high <>", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThan(Double value) {
            addCriterion("high >", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThanOrEqualTo(Double value) {
            addCriterion("high >=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThan(Double value) {
            addCriterion("high <", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThanOrEqualTo(Double value) {
            addCriterion("high <=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighIn(List<Double> values) {
            addCriterion("high in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotIn(List<Double> values) {
            addCriterion("high not in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighBetween(Double value1, Double value2) {
            addCriterion("high between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotBetween(Double value1, Double value2) {
            addCriterion("high not between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andCloseIsNull() {
            addCriterion("close is null");
            return (Criteria) this;
        }

        public Criteria andCloseIsNotNull() {
            addCriterion("close is not null");
            return (Criteria) this;
        }

        public Criteria andCloseEqualTo(Double value) {
            addCriterion("close =", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseNotEqualTo(Double value) {
            addCriterion("close <>", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseGreaterThan(Double value) {
            addCriterion("close >", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseGreaterThanOrEqualTo(Double value) {
            addCriterion("close >=", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseLessThan(Double value) {
            addCriterion("close <", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseLessThanOrEqualTo(Double value) {
            addCriterion("close <=", value, "close");
            return (Criteria) this;
        }

        public Criteria andCloseIn(List<Double> values) {
            addCriterion("close in", values, "close");
            return (Criteria) this;
        }

        public Criteria andCloseNotIn(List<Double> values) {
            addCriterion("close not in", values, "close");
            return (Criteria) this;
        }

        public Criteria andCloseBetween(Double value1, Double value2) {
            addCriterion("close between", value1, value2, "close");
            return (Criteria) this;
        }

        public Criteria andCloseNotBetween(Double value1, Double value2) {
            addCriterion("close not between", value1, value2, "close");
            return (Criteria) this;
        }

        public Criteria andLowIsNull() {
            addCriterion("low is null");
            return (Criteria) this;
        }

        public Criteria andLowIsNotNull() {
            addCriterion("low is not null");
            return (Criteria) this;
        }

        public Criteria andLowEqualTo(Double value) {
            addCriterion("low =", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowNotEqualTo(Double value) {
            addCriterion("low <>", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowGreaterThan(Double value) {
            addCriterion("low >", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowGreaterThanOrEqualTo(Double value) {
            addCriterion("low >=", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowLessThan(Double value) {
            addCriterion("low <", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowLessThanOrEqualTo(Double value) {
            addCriterion("low <=", value, "low");
            return (Criteria) this;
        }

        public Criteria andLowIn(List<Double> values) {
            addCriterion("low in", values, "low");
            return (Criteria) this;
        }

        public Criteria andLowNotIn(List<Double> values) {
            addCriterion("low not in", values, "low");
            return (Criteria) this;
        }

        public Criteria andLowBetween(Double value1, Double value2) {
            addCriterion("low between", value1, value2, "low");
            return (Criteria) this;
        }

        public Criteria andLowNotBetween(Double value1, Double value2) {
            addCriterion("low not between", value1, value2, "low");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(Double value) {
            addCriterion("volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(Double value) {
            addCriterion("volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(Double value) {
            addCriterion("volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(Double value) {
            addCriterion("volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(Double value) {
            addCriterion("volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<Double> values) {
            addCriterion("volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<Double> values) {
            addCriterion("volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(Double value1, Double value2) {
            addCriterion("volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(Double value1, Double value2) {
            addCriterion("volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andPriceChangeIsNull() {
            addCriterion("price_change is null");
            return (Criteria) this;
        }

        public Criteria andPriceChangeIsNotNull() {
            addCriterion("price_change is not null");
            return (Criteria) this;
        }

        public Criteria andPriceChangeEqualTo(Double value) {
            addCriterion("price_change =", value, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeNotEqualTo(Double value) {
            addCriterion("price_change <>", value, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeGreaterThan(Double value) {
            addCriterion("price_change >", value, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeGreaterThanOrEqualTo(Double value) {
            addCriterion("price_change >=", value, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeLessThan(Double value) {
            addCriterion("price_change <", value, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeLessThanOrEqualTo(Double value) {
            addCriterion("price_change <=", value, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeIn(List<Double> values) {
            addCriterion("price_change in", values, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeNotIn(List<Double> values) {
            addCriterion("price_change not in", values, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeBetween(Double value1, Double value2) {
            addCriterion("price_change between", value1, value2, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPriceChangeNotBetween(Double value1, Double value2) {
            addCriterion("price_change not between", value1, value2, "priceChange");
            return (Criteria) this;
        }

        public Criteria andPChangeIsNull() {
            addCriterion("p_change is null");
            return (Criteria) this;
        }

        public Criteria andPChangeIsNotNull() {
            addCriterion("p_change is not null");
            return (Criteria) this;
        }

        public Criteria andPChangeEqualTo(Double value) {
            addCriterion("p_change =", value, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeNotEqualTo(Double value) {
            addCriterion("p_change <>", value, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeGreaterThan(Double value) {
            addCriterion("p_change >", value, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeGreaterThanOrEqualTo(Double value) {
            addCriterion("p_change >=", value, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeLessThan(Double value) {
            addCriterion("p_change <", value, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeLessThanOrEqualTo(Double value) {
            addCriterion("p_change <=", value, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeIn(List<Double> values) {
            addCriterion("p_change in", values, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeNotIn(List<Double> values) {
            addCriterion("p_change not in", values, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeBetween(Double value1, Double value2) {
            addCriterion("p_change between", value1, value2, "pChange");
            return (Criteria) this;
        }

        public Criteria andPChangeNotBetween(Double value1, Double value2) {
            addCriterion("p_change not between", value1, value2, "pChange");
            return (Criteria) this;
        }

        public Criteria andMa5IsNull() {
            addCriterion("ma5 is null");
            return (Criteria) this;
        }

        public Criteria andMa5IsNotNull() {
            addCriterion("ma5 is not null");
            return (Criteria) this;
        }

        public Criteria andMa5EqualTo(Double value) {
            addCriterion("ma5 =", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5NotEqualTo(Double value) {
            addCriterion("ma5 <>", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5GreaterThan(Double value) {
            addCriterion("ma5 >", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5GreaterThanOrEqualTo(Double value) {
            addCriterion("ma5 >=", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5LessThan(Double value) {
            addCriterion("ma5 <", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5LessThanOrEqualTo(Double value) {
            addCriterion("ma5 <=", value, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5In(List<Double> values) {
            addCriterion("ma5 in", values, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5NotIn(List<Double> values) {
            addCriterion("ma5 not in", values, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5Between(Double value1, Double value2) {
            addCriterion("ma5 between", value1, value2, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa5NotBetween(Double value1, Double value2) {
            addCriterion("ma5 not between", value1, value2, "ma5");
            return (Criteria) this;
        }

        public Criteria andMa10IsNull() {
            addCriterion("ma10 is null");
            return (Criteria) this;
        }

        public Criteria andMa10IsNotNull() {
            addCriterion("ma10 is not null");
            return (Criteria) this;
        }

        public Criteria andMa10EqualTo(Double value) {
            addCriterion("ma10 =", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10NotEqualTo(Double value) {
            addCriterion("ma10 <>", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10GreaterThan(Double value) {
            addCriterion("ma10 >", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10GreaterThanOrEqualTo(Double value) {
            addCriterion("ma10 >=", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10LessThan(Double value) {
            addCriterion("ma10 <", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10LessThanOrEqualTo(Double value) {
            addCriterion("ma10 <=", value, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10In(List<Double> values) {
            addCriterion("ma10 in", values, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10NotIn(List<Double> values) {
            addCriterion("ma10 not in", values, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10Between(Double value1, Double value2) {
            addCriterion("ma10 between", value1, value2, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa10NotBetween(Double value1, Double value2) {
            addCriterion("ma10 not between", value1, value2, "ma10");
            return (Criteria) this;
        }

        public Criteria andMa20IsNull() {
            addCriterion("ma20 is null");
            return (Criteria) this;
        }

        public Criteria andMa20IsNotNull() {
            addCriterion("ma20 is not null");
            return (Criteria) this;
        }

        public Criteria andMa20EqualTo(Double value) {
            addCriterion("ma20 =", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20NotEqualTo(Double value) {
            addCriterion("ma20 <>", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20GreaterThan(Double value) {
            addCriterion("ma20 >", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20GreaterThanOrEqualTo(Double value) {
            addCriterion("ma20 >=", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20LessThan(Double value) {
            addCriterion("ma20 <", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20LessThanOrEqualTo(Double value) {
            addCriterion("ma20 <=", value, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20In(List<Double> values) {
            addCriterion("ma20 in", values, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20NotIn(List<Double> values) {
            addCriterion("ma20 not in", values, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20Between(Double value1, Double value2) {
            addCriterion("ma20 between", value1, value2, "ma20");
            return (Criteria) this;
        }

        public Criteria andMa20NotBetween(Double value1, Double value2) {
            addCriterion("ma20 not between", value1, value2, "ma20");
            return (Criteria) this;
        }

        public Criteria andVMa5IsNull() {
            addCriterion("v_ma5 is null");
            return (Criteria) this;
        }

        public Criteria andVMa5IsNotNull() {
            addCriterion("v_ma5 is not null");
            return (Criteria) this;
        }

        public Criteria andVMa5EqualTo(Double value) {
            addCriterion("v_ma5 =", value, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5NotEqualTo(Double value) {
            addCriterion("v_ma5 <>", value, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5GreaterThan(Double value) {
            addCriterion("v_ma5 >", value, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5GreaterThanOrEqualTo(Double value) {
            addCriterion("v_ma5 >=", value, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5LessThan(Double value) {
            addCriterion("v_ma5 <", value, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5LessThanOrEqualTo(Double value) {
            addCriterion("v_ma5 <=", value, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5In(List<Double> values) {
            addCriterion("v_ma5 in", values, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5NotIn(List<Double> values) {
            addCriterion("v_ma5 not in", values, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5Between(Double value1, Double value2) {
            addCriterion("v_ma5 between", value1, value2, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa5NotBetween(Double value1, Double value2) {
            addCriterion("v_ma5 not between", value1, value2, "vMa5");
            return (Criteria) this;
        }

        public Criteria andVMa10IsNull() {
            addCriterion("v_ma10 is null");
            return (Criteria) this;
        }

        public Criteria andVMa10IsNotNull() {
            addCriterion("v_ma10 is not null");
            return (Criteria) this;
        }

        public Criteria andVMa10EqualTo(Double value) {
            addCriterion("v_ma10 =", value, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10NotEqualTo(Double value) {
            addCriterion("v_ma10 <>", value, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10GreaterThan(Double value) {
            addCriterion("v_ma10 >", value, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10GreaterThanOrEqualTo(Double value) {
            addCriterion("v_ma10 >=", value, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10LessThan(Double value) {
            addCriterion("v_ma10 <", value, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10LessThanOrEqualTo(Double value) {
            addCriterion("v_ma10 <=", value, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10In(List<Double> values) {
            addCriterion("v_ma10 in", values, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10NotIn(List<Double> values) {
            addCriterion("v_ma10 not in", values, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10Between(Double value1, Double value2) {
            addCriterion("v_ma10 between", value1, value2, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa10NotBetween(Double value1, Double value2) {
            addCriterion("v_ma10 not between", value1, value2, "vMa10");
            return (Criteria) this;
        }

        public Criteria andVMa20IsNull() {
            addCriterion("v_ma20 is null");
            return (Criteria) this;
        }

        public Criteria andVMa20IsNotNull() {
            addCriterion("v_ma20 is not null");
            return (Criteria) this;
        }

        public Criteria andVMa20EqualTo(Double value) {
            addCriterion("v_ma20 =", value, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20NotEqualTo(Double value) {
            addCriterion("v_ma20 <>", value, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20GreaterThan(Double value) {
            addCriterion("v_ma20 >", value, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20GreaterThanOrEqualTo(Double value) {
            addCriterion("v_ma20 >=", value, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20LessThan(Double value) {
            addCriterion("v_ma20 <", value, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20LessThanOrEqualTo(Double value) {
            addCriterion("v_ma20 <=", value, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20In(List<Double> values) {
            addCriterion("v_ma20 in", values, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20NotIn(List<Double> values) {
            addCriterion("v_ma20 not in", values, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20Between(Double value1, Double value2) {
            addCriterion("v_ma20 between", value1, value2, "vMa20");
            return (Criteria) this;
        }

        public Criteria andVMa20NotBetween(Double value1, Double value2) {
            addCriterion("v_ma20 not between", value1, value2, "vMa20");
            return (Criteria) this;
        }

        public Criteria andTurnoverIsNull() {
            addCriterion("turnover is null");
            return (Criteria) this;
        }

        public Criteria andTurnoverIsNotNull() {
            addCriterion("turnover is not null");
            return (Criteria) this;
        }

        public Criteria andTurnoverEqualTo(Double value) {
            addCriterion("turnover =", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverNotEqualTo(Double value) {
            addCriterion("turnover <>", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverGreaterThan(Double value) {
            addCriterion("turnover >", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverGreaterThanOrEqualTo(Double value) {
            addCriterion("turnover >=", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverLessThan(Double value) {
            addCriterion("turnover <", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverLessThanOrEqualTo(Double value) {
            addCriterion("turnover <=", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverIn(List<Double> values) {
            addCriterion("turnover in", values, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverNotIn(List<Double> values) {
            addCriterion("turnover not in", values, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverBetween(Double value1, Double value2) {
            addCriterion("turnover between", value1, value2, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverNotBetween(Double value1, Double value2) {
            addCriterion("turnover not between", value1, value2, "turnover");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_quotation
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 08 11:23:13 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_quotation
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}