package com.htsc.hub.db.model;

public class StockAssets {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_assets.Id
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_assets.init_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	private Float initAssets;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_assets.stock_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	private Float stockAssets;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_assets.cash_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	private Float cashAssets;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_assets.profit
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	private Float profit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_assets.Id
	 * @return  the value of stock_assets.Id
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_assets.Id
	 * @param id  the value for stock_assets.Id
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_assets.init_assets
	 * @return  the value of stock_assets.init_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public Float getInitAssets() {
		return initAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_assets.init_assets
	 * @param initAssets  the value for stock_assets.init_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public void setInitAssets(Float initAssets) {
		this.initAssets = initAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_assets.stock_assets
	 * @return  the value of stock_assets.stock_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public Float getStockAssets() {
		return stockAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_assets.stock_assets
	 * @param stockAssets  the value for stock_assets.stock_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public void setStockAssets(Float stockAssets) {
		this.stockAssets = stockAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_assets.cash_assets
	 * @return  the value of stock_assets.cash_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public Float getCashAssets() {
		return cashAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_assets.cash_assets
	 * @param cashAssets  the value for stock_assets.cash_assets
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public void setCashAssets(Float cashAssets) {
		this.cashAssets = cashAssets;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_assets.profit
	 * @return  the value of stock_assets.profit
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public Float getProfit() {
		return profit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_assets.profit
	 * @param profit  the value for stock_assets.profit
	 * @mbggenerated  Sat Feb 13 20:08:52 CST 2016
	 */
	public void setProfit(Float profit) {
		this.profit = profit;
	}
}