package com.htsc.hub.db.model;

public class StockQuotation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.code
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.name
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.date
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.open
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.high
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.close
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.low
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.volume
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.price_change
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float priceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.p_change
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float pChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.ma5
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float ma5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.ma10
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float ma10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.ma20
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float ma20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.v_ma5
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float vMa5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.v_ma10
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float vMa10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.v_ma20
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float vMa20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation.turnover
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    private float turnover;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.code
     *
     * @return the value of stock_quotation.code
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.code
     *
     * @param code the value for stock_quotation.code
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.name
     *
     * @return the value of stock_quotation.name
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.name
     *
     * @param name the value for stock_quotation.name
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.date
     *
     * @return the value of stock_quotation.date
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.date
     *
     * @param date the value for stock_quotation.date
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.open
     *
     * @return the value of stock_quotation.open
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.open
     *
     * @param open the value for stock_quotation.open
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setOpen(float open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.high
     *
     * @return the value of stock_quotation.high
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.high
     *
     * @param high the value for stock_quotation.high
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setHigh(float high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.close
     *
     * @return the value of stock_quotation.close
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.close
     *
     * @param close the value for stock_quotation.close
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setClose(float close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.low
     *
     * @return the value of stock_quotation.low
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.low
     *
     * @param low the value for stock_quotation.low
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setLow(float low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.volume
     *
     * @return the value of stock_quotation.volume
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.volume
     *
     * @param volume the value for stock_quotation.volume
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setVolume(float volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.price_change
     *
     * @return the value of stock_quotation.price_change
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getPriceChange() {
        return priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.price_change
     *
     * @param priceChange the value for stock_quotation.price_change
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setPriceChange(float priceChange) {
        this.priceChange = priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.p_change
     *
     * @return the value of stock_quotation.p_change
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getpChange() {
        return pChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.p_change
     *
     * @param pChange the value for stock_quotation.p_change
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setpChange(float pChange) {
        this.pChange = pChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.ma5
     *
     * @return the value of stock_quotation.ma5
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getMa5() {
        return ma5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.ma5
     *
     * @param ma5 the value for stock_quotation.ma5
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setMa5(float ma5) {
        this.ma5 = ma5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.ma10
     *
     * @return the value of stock_quotation.ma10
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getMa10() {
        return ma10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.ma10
     *
     * @param ma10 the value for stock_quotation.ma10
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setMa10(float ma10) {
        this.ma10 = ma10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.ma20
     *
     * @return the value of stock_quotation.ma20
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getMa20() {
        return ma20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.ma20
     *
     * @param ma20 the value for stock_quotation.ma20
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setMa20(float ma20) {
        this.ma20 = ma20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.v_ma5
     *
     * @return the value of stock_quotation.v_ma5
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getvMa5() {
        return vMa5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.v_ma5
     *
     * @param vMa5 the value for stock_quotation.v_ma5
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setvMa5(float vMa5) {
        this.vMa5 = vMa5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.v_ma10
     *
     * @return the value of stock_quotation.v_ma10
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getvMa10() {
        return vMa10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.v_ma10
     *
     * @param vMa10 the value for stock_quotation.v_ma10
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setvMa10(float vMa10) {
        this.vMa10 = vMa10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.v_ma20
     *
     * @return the value of stock_quotation.v_ma20
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getvMa20() {
        return vMa20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.v_ma20
     *
     * @param vMa20 the value for stock_quotation.v_ma20
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setvMa20(float vMa20) {
        this.vMa20 = vMa20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation.turnover
     *
     * @return the value of stock_quotation.turnover
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public float getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation.turnover
     *
     * @param turnover the value for stock_quotation.turnover
     *
     * @mbggenerated Mon Feb 08 11:23:13 CST 2016
     */
    public void setTurnover(float turnover) {
        this.turnover = turnover;
    }
}