package com.htsc.hub.db.model;

public class StockQuotationQ {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.code
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.name
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.date
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.open
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private Float open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.high
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private Float high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.close
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private Float close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.low
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private Float low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.volume
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private Float volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_quotation_q.amount
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    private Float amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.code
     *
     * @return the value of stock_quotation_q.code
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.code
     *
     * @param code the value for stock_quotation_q.code
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.name
     *
     * @return the value of stock_quotation_q.name
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.name
     *
     * @param name the value for stock_quotation_q.name
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.date
     *
     * @return the value of stock_quotation_q.date
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.date
     *
     * @param date the value for stock_quotation_q.date
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.open
     *
     * @return the value of stock_quotation_q.open
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public Float getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.open
     *
     * @param open the value for stock_quotation_q.open
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setOpen(Float open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.high
     *
     * @return the value of stock_quotation_q.high
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public Float getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.high
     *
     * @param high the value for stock_quotation_q.high
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setHigh(Float high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.close
     *
     * @return the value of stock_quotation_q.close
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public Float getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.close
     *
     * @param close the value for stock_quotation_q.close
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setClose(Float close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.low
     *
     * @return the value of stock_quotation_q.low
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public Float getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.low
     *
     * @param low the value for stock_quotation_q.low
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setLow(Float low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.volume
     *
     * @return the value of stock_quotation_q.volume
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public Float getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.volume
     *
     * @param volume the value for stock_quotation_q.volume
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setVolume(Float volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quotation_q.amount
     *
     * @return the value of stock_quotation_q.amount
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quotation_q.amount
     *
     * @param amount the value for stock_quotation_q.amount
     *
     * @mbggenerated Thu Mar 10 13:24:50 CST 2016
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }
}