package com.htsc.hub.db.model;

public class StockWeekDay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_week_day.Id
     *
     * @mbggenerated Wed Feb 17 14:15:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_week_day.date
     *
     * @mbggenerated Wed Feb 17 14:15:52 CST 2016
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_week_day.Id
     *
     * @return the value of stock_week_day.Id
     *
     * @mbggenerated Wed Feb 17 14:15:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_week_day.Id
     *
     * @param id the value for stock_week_day.Id
     *
     * @mbggenerated Wed Feb 17 14:15:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_week_day.date
     *
     * @return the value of stock_week_day.date
     *
     * @mbggenerated Wed Feb 17 14:15:52 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_week_day.date
     *
     * @param date the value for stock_week_day.date
     *
     * @mbggenerated Wed Feb 17 14:15:52 CST 2016
     */
    public void setDate(String date) {
        this.date = date;
    }
}