package com.htsc.hub.db.model;

public class StockOps {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ops.Id
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ops.code
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ops.date
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_ops.type
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ops.Id
     *
     * @return the value of stock_ops.Id
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ops.Id
     *
     * @param id the value for stock_ops.Id
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ops.code
     *
     * @return the value of stock_ops.code
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ops.code
     *
     * @param code the value for stock_ops.code
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ops.date
     *
     * @return the value of stock_ops.date
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ops.date
     *
     * @param date the value for stock_ops.date
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_ops.type
     *
     * @return the value of stock_ops.type
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_ops.type
     *
     * @param type the value for stock_ops.type
     *
     * @mbggenerated Sat Feb 13 20:08:52 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }
}