package com.htsc.hub.db.model;

public class StockDate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_date.Id
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_date.date
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	private String date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock_date.day
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	private Integer day;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_date.Id
	 * @return  the value of stock_date.Id
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_date.Id
	 * @param id  the value for stock_date.Id
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_date.date
	 * @return  the value of stock_date.date
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_date.date
	 * @param date  the value for stock_date.date
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock_date.day
	 * @return  the value of stock_date.day
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	public Integer getDay() {
		return day;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock_date.day
	 * @param day  the value for stock_date.day
	 * @mbggenerated  Wed Feb 17 13:44:58 CST 2016
	 */
	public void setDay(Integer day) {
		this.day = day;
	}
}